config/routes.rb
Rails.application.routes.draw do
  root to: "authors#index"

  resources :authors
  resources :books
end

app/models/author.rb
class Author
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :age, type: Integer
end

app/models/book.rb
class Book
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	def index
		@authors = Author.all
	end

	def show
		@author = Author.find(params[:id])
	end

  def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)
    if @author.save
      redirect_to root_path
    else
      render :new
    end
	end

  def destroy
    @author.destroy
    redirect_to root_path
  end

	private

	def author_params
		params.require(:author).permit(:name, :age)
	end

  def set_author
    @author = Author.find(params[:id])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
  <%= simple_form_for author do |f| %>
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/authors/index.html.erb
<div class="container mt-5">
  <% @authors.each do |author| %>
    <%= link_to author_path(author.id) do %>
    <p><%= author.name %></p>
    <% end %>
  <% end %>
</div>

app/views/authors/new.html.erb
<div class="container">
  <%= render 'form', author: @author %>
</div>

app/views/authors/show.html.erb
<div class="container">
  <%= @author.name %>
</div>

app/views/books/_form.html.erb
<%= simple_form_for book do |f| %>
    <%= f.input :title %>
    <%= f.collection_select(:author_id, Author.all, :id, :name) %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/books/index.html.erb
<div class="container mt-5">
  <% @books.each do |book| %>
    <%= link_to book_path(book.id) do %>
    <p><%= book.title %></p>
    <% end %>
  <% end %>
</div>

app/views/books/new.html.erb
<%= render 'form', book: @book %>

app/views/books/show.html.erb
<div class="container mt-5">
  <p>
    <strong>Name:</strong>
    <%= @book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= @book.author.name %>
  </p>

  <%= link_to "Edit book", edit_book_path(@book.id), class: "btn btn-info" %>
  <%= link_to "New Book", new_book_path, class: "btn btn-primary" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MongoAPP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>